import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/component/NavBar";
import Footer from "@/component/Footer";
import PageLoader from "@/component/PageLoader";
import { PageTransitionProvider } from "@/component/PageTransitionProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Purple Club",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased bg-[#d4ff3f]`}
    >
      <PageTransitionProvider>   <PageLoader/>

      <Navbar/>
      <body className="min-h-full flex flex-col">{children}

       <Footer/> 
       
      </body>
      </PageTransitionProvider>

    </html>
  );
}
