
import Navbar from "@/component/NavBar";
import Footer from "@/component/Footer";
import PageLoader from "@/component/PageLoader";



export const metadata = {
  title: "Purple Club",
  description: "Generated by create next app",
};

export default function Layout({ children }) {
  return (

<>
    <PageLoader/>
          <Navbar/>
        {children}
       <Footer/> 
       
     
   </>
  );
}
